name: online_trading
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animated_page_reveal: ^1.0.0
  bottom_bar: ^2.0.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  dart_amqp: ^0.2.5 
  encrypt: ^5.0.1
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_multi_formatter: ^2.11.11
  flutter_pin_code_fields: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.0
  flutter_switch: ^0.3.2
  get: ^4.6.5
  horizontal_data_table: ^4.3.1
  icons_launcher: ^2.1.4
  in_date_utils: ^1.2.0+2
  intl: ^0.18.0
  k_chart: ^0.7.1
  local_auth: ^2.1.7
  lottie: ^2.6.0 
  network_info_plus: ^4.0.1
  objectbox: ^2.1.0
  objectbox_flutter_libs: ^2.1.0
  open_file: ^3.3.2
  package_info_plus: ^4.0.2
  page_transition: ^2.0.9
  path_provider: ^2.0.15
  pdf: ^3.10.4
  persistent_bottom_nav_bar: ^5.0.2
  pinput: ^3.0.1
  printing: ^5.11.0
  restart_app: ^1.2.1
  searchfield: ^0.8.3
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  syncfusion_flutter_charts: ^23.1.36
  syncfusion_flutter_pdf: ^23.1.36
  syncfusion_flutter_pdfviewer: ^23.1.36
  synchronized: ^3.1.0
  universal_platform: ^1.0.0+1
  window_manager: ^0.3.6
  wolt_modal_sheet: ^0.0.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/images/

icons_launcher:
  image_path: "assets/logo/logo Stamp Evergreen warna hijau 192.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

# flutter_native_splash:
#   android: true
#   ios: true
#   web: false
#   color: "#00F700"
#   # background_image:
#   image: "assets/images/under-construction.png"
#   android_12:
#     color: "#00F700"
#     image: "assets/images/under-construction.png"
